name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  upload-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: bin-artifact
    - name: Display structure of downloaded files
      run: ls -R


  build_run_linux_sp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make FOO=-fno-stack-protector
    - name: run
      run: ./main

  build_run_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: run
      run: ./main
    - uses: actions/upload-artifact@v2
      with:
        name: bin-artifact
        path: ./main

  build_run_win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: main
      run: ./main.exe skip
    - uses: actions/upload-artifact@v2
      with:
        name: bin-artifact
        path: ./main.exe
  