name: Release

on:
  push:
    tags:
      - "v*"

jobs:

  upload-release:

    runs-on: ubuntu-latest
    needs: [build_run_linux, build_run_win]

    steps:
    #- uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: bin-artifact
    - name: Display structure of downloaded files
      run: ls -R
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: main*

  build_run_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: run
      run: ./main
    - uses: actions/upload-artifact@v2
      with:
        name: bin-artifact
        path: ./main

  build_run_win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: main
      run: ./main.exe skip
    - uses: actions/upload-artifact@v2
      with:
        name: bin-artifact
        path: ./main.exe
  